name: Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: k8s-amd64
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"
      - run: npm ci
      - run: npm run check

      - name: Validate the test-stage Dockerfile still builds
        uses: mattjmorrison-homelab/actions-k8s@417ba5ccf6d3be8e24d4bc11f82618b1c280c967 # main
        with:
          service-account: ui-hdmi-switch-job
          image: gcr.io/kaniko-project/executor@sha256:4e7a52dd1f14872430652bb3b027405b8dfd17c4538751c620ac005741ef9698
          shell: "false"
          command: >-
            --context=git://github.com/mattjmorrison-homelab/ui-hdmi-switch.git#refs/heads/${{ github.head_ref }}
            --dockerfile=Dockerfile --target=test --no-push

      - name: Validate the release-stage Dockerfile still builds
        uses: mattjmorrison-homelab/actions-k8s@417ba5ccf6d3be8e24d4bc11f82618b1c280c967 # main
        with:
          service-account: ui-hdmi-switch-job
          image: gcr.io/kaniko-project/executor@sha256:4e7a52dd1f14872430652bb3b027405b8dfd17c4538751c620ac005741ef9698
          shell: "false"
          command: >-
            --context=git://github.com/mattjmorrison-homelab/ui-hdmi-switch.git#refs/heads/${{ github.head_ref }}
            --dockerfile=Dockerfile --target=release --build-arg=COMMIT_SHA=${{ github.event.pull_request.head.sha }} --no-push
